2024-08-28 02:24:09,710 - ERROR - unpack requires a buffer of 752 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 752 bytes
2024-08-28 02:24:09,722 - ERROR - unpack requires a buffer of 832 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 832 bytes
2024-08-28 02:24:09,745 - ERROR - unpack requires a buffer of 752 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 752 bytes
2024-08-28 02:24:09,746 - ERROR - unpack requires a buffer of 384 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 384 bytes
2024-08-28 02:24:09,782 - ERROR - unpack requires a buffer of 32 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1319, in __shape
    record.bbox = _Array('d', unpack("<4d", f.read(32)))
struct.error: unpack requires a buffer of 32 bytes
2024-08-28 02:24:09,782 - ERROR - unpack requires a buffer of 256 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 256 bytes
2024-08-28 02:24:09,801 - ERROR - unpack requires a buffer of 160 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 160 bytes
2024-08-28 02:24:11,270 - ERROR - unpack requires a buffer of 32 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1319, in __shape
    record.bbox = _Array('d', unpack("<4d", f.read(32)))
struct.error: unpack requires a buffer of 32 bytes
2024-08-28 02:24:11,997 - ERROR - unpack requires a buffer of 105712 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 105712 bytes
2024-08-28 02:24:12,000 - ERROR - unpack requires a buffer of 912 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 912 bytes
2024-08-28 02:26:06,622 - ERROR - unpack requires a buffer of 912 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 912 bytes
2024-08-28 02:26:09,860 - ERROR - unpack requires a buffer of 54224 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 54224 bytes
2024-08-28 02:26:10,299 - ERROR - unpack requires a buffer of 65904 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 65904 bytes
2024-08-28 02:26:10,322 - ERROR - unpack requires a buffer of 15440 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 15440 bytes
2024-08-28 02:26:11,603 - ERROR - unpack requires a buffer of 432 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 432 bytes
2024-08-28 02:26:11,649 - ERROR - unpack requires a buffer of 240 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 240 bytes
2024-08-28 02:26:13,197 - ERROR - unpack requires a buffer of 10736 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 10736 bytes
2024-08-28 02:26:13,197 - ERROR - unpack requires a buffer of 224928 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 224928 bytes
2024-08-28 02:26:13,508 - ERROR - unpack requires a buffer of 125024 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 125024 bytes
2024-08-28 02:26:14,093 - ERROR - unpack requires a buffer of 592 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 592 bytes
2024-08-28 02:26:14,095 - ERROR - unpack requires a buffer of 8 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1309, in __shape
    (recNum, recLength) = unpack(">2i", f.read(8))
struct.error: unpack requires a buffer of 8 bytes
2024-08-28 02:26:15,391 - ERROR - unpack requires a buffer of 240 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 240 bytes
2024-08-28 02:26:18,411 - ERROR - unpack requires a buffer of 3712 bytes
Traceback (most recent call last):
  File "/app/_gen_image.py", line 52, in generate_image
    plt.savefig(f"image/all/{timestamp}.jpg", dpi=150, bbox_inches='tight')
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2164, in print_figure
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 535, in draw
    return super().draw(renderer=renderer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/mpl/feature_artist.py", line 152, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 305, in intersecting_geometries
    return super().intersecting_geometries(extent)
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 108, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/opt/conda/lib/python3.10/site-packages/cartopy/feature/__init__.py", line 290, in geometries
    geometries = tuple(shapereader.Reader(path).geometries())
  File "/opt/conda/lib/python3.10/site-packages/cartopy/io/shapereader.py", line 161, in geometries
    for shape in self._reader.iterShapes():
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1483, in iterShapes
    shape = self.__shape(oid=i, bbox=bbox)
  File "/opt/conda/lib/python3.10/site-packages/shapefile.py", line 1340, in __shape
    flat = unpack("<%sd" % (2 * nPoints), f.read(16*nPoints))
struct.error: unpack requires a buffer of 3712 bytes
2024-08-28 02:33:01,435 - ERROR - Error tokenizing data. C error: Expected 6 fields in line 3427, saw 7
Traceback (most recent call last):
  File "/app/_gen_image.py", line 95, in <module>
    for chunk in metadata_chunks:
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1843, in __next__
    return self.get_chunk()
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1985, in get_chunk
    return self.read(nrows=size)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "parsers.pyx", line 850, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 6 fields in line 3427, saw 7

